version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    build:
      context: .
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"

volumes:
  dbdata: